package ui

import "html/template"

const registerPageHTML = `<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Регистрация | CmdUI</title><style>
:root{font-family:"IBM Plex Sans","Segoe UI",sans-serif;color:#27312d;background:#f5f7f5;font-synthesis:none}*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;padding:24px}.login{width:min(100%,390px);background:#fff;border:1px solid #e0e6e1;padding:32px;border-radius:8px}.brand{font-size:14px;font-weight:700;color:#16845b}.login h1{font-size:24px;margin:22px 0 6px}.muted{color:#69746e;font-size:14px;margin:0 0 24px}label{display:block;font-size:13px;font-weight:600;margin:16px 0 7px}input{width:100%;height:42px;border:1px solid #cfd8d1;border-radius:5px;padding:0 12px;font:inherit}button{margin-top:22px;width:100%;height:42px;background:#147b54;color:#fff;border:0;border-radius:5px;font:inherit;font-weight:600;cursor:pointer}.error{margin-top:16px;padding:10px 12px;background:#fff2f0;color:#a33b2c;border-left:3px solid #d45a48;font-size:14px}.link{display:block;margin-top:18px;text-align:center;color:#147b54}
</style></head><body><main class="login"><div class="brand">CMDUI <span style="color:#69746e;font-weight:400">/ Регистрация</span></div><h1>Создать аккаунт</h1><p class="muted">Новая учетная запись получит права только на просмотр доступных команд.</p><form method="post" action="/register"><label for="username">Логин</label><input id="username" name="username" autocomplete="username" minlength="4" maxlength="32" pattern="[A-Za-zА-Яа-яЁё0-9._\-]+" required autofocus><label for="password">Пароль</label><input id="password" name="password" type="password" autocomplete="new-password" minlength="4" required><label for="password_confirm">Повторите пароль</label><input id="password_confirm" name="password_confirm" type="password" autocomplete="new-password" minlength="4" required><button type="submit">Зарегистрироваться</button></form>{{with .Error}}<div class="error">{{.}}</div>{{end}}<a class="link" href="/login">Уже есть аккаунт? Войти</a></main></body></html>`

var RegisterTemplate = template.Must(template.New("register").Parse(withSharedStylesheet(registerPageHTML)))
